# Generated by Django 5.1 on 2024-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contact_options_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('career', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('image', models.ImageField(upload_to='images/teamprof', verbose_name='تصویر')),
                ('text', models.CharField(max_length=200, verbose_name='توضیحات')),
            ],
        ),
    ]
