# Generated by Django 5.1 on 2024-10-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
    ]
