# Generated by Django 5.1 on 2024-10-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='images/services/main', verbose_name='تصویر اصلی')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/services/1', verbose_name='تصویر متن 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/services/2', verbose_name='تصویر متن 2')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
