# Generated by Django 5.1 on 2024-10-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created',), 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
    ]
