# Generated by Django 5.1 on 2024-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_service_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='service',
            name='body2',
            field=models.TextField(blank=True, null=True, verbose_name='متن اضافه'),
        ),
    ]
