# Generated by Django 5.1 on 2024-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_body_service_body1_service_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, default='static/images/services-details-image/1.png', null=True, upload_to='images/services/1', verbose_name='تصویر متن 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, default='static/images/services-details-image/2.png', null=True, upload_to='images/services/2', verbose_name='تصویر متن 2'),
        ),
    ]
