# Generated by Django 5.1 on 2024-10-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_service_image1_alter_service_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, default='media/images/services/1/1-default.png', null=True, upload_to='images/services/1', verbose_name='تصویر متن 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, default='media/images/services/2/2-default.png', null=True, upload_to='images/services/2', verbose_name='تصویر متن 2'),
        ),
    ]
