# Generated by Django 5.1 on 2024-10-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_service_image1_alter_service_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(max_length=200, verbose_name='معرفی مختصر')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='images/samples', verbose_name='تصویر')),
                ('customer', models.CharField(max_length=100, verbose_name='مشتری')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انجام پروژه')),
            ],
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/samples', verbose_name='تصویر')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.sample', verbose_name='نمونه کار')),
            ],
        ),
    ]
