# Generated by Django 5.1 on 2024-10-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_sample_sampleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-date',), 'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.AlterModelOptions(
            name='sampleimage',
            options={'verbose_name': 'تصویر متن نمونه کار', 'verbose_name_plural': 'تصاویر متن نمونه کار'},
        ),
    ]
